library("tximport")
library("DESeq2")
library("pheatmap")
library("RColorBrewer")
library("gplots")
samples                          <- read.csv("metadata.tsv",header=TRUE,sep="\t")
files                            <- file.path(".", samples$sample,"abundance.tsv")
names(files)                     <- samples$sample
tx2gene                          <- read.csv("tx2gene.tsv",sep="\t",header=TRUE)
txi_kallisto                     <- tximport(files, type = "kallisto", tx2gene=tx2gene)
sampleNames                      <- c("RT1SL1SS01","RT1SL1SS02","RT1SL1SS03","RT1SL1SS04","RT1SL1SS05","RT1SL1SS06")
sampleGroup                      <- c("control","control","control","treatment","treatment","treatment")
sampleTable                      <- data.frame(sample=sampleNames, dex=sampleGroup)
rownames(sampleTable)            <- colnames(txi_kallisto$counts)
ddsTxi                           <- DESeqDataSetFromTximport(txi_kallisto,sampleTable,design=~dex)
dds                              <- DESeq(ddsTxi)
res                              <- results(dds)
nsub                             <- nrow(dds)
rld                              <- rlog(dds,blind=TRUE)
vsd                              <- vst(dds,blind=TRUE)
sample_vsd_dists                 <- dist(t(assay(vsd)))
sample_vsd_dist_matrix           <- as.matrix( sample_vsd_dists )
sig_de_gene_matrix               <- res[!is.na(res$padj) & res$padj<0.05 & abs(res$log2FoldChange)>=1,]
write.table(sig_de_gene_matrix,file="differentially_expressed_genes.kallisto.tsv", quote=FALSE, sep="\t")
sig_de_gene_names                <- rownames(sig_de_gene_matrix)
sig_de_gene_df                   <- counts(dds)[rownames(dds) %in% sig_de_gene_names,]
row_sub                          <- apply(sig_de_gene_df,1,function(row)all(row !=0 ))
sig_de_gene_df                   <-sig_de_gene_df[row_sub,]
rownames(sample_vsd_dist_matrix) <- paste( vsd$dex, colnames(vsd), sep = "-" )
colnames(sample_vsd_dist_matrix) <- NULL
vsd_colors                       <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
sample_rld_dists                 <- dist(t(assay(rld)))
sample_rld_dist_matrix           <- as.matrix( sample_rld_dists )
rownames(sample_rld_dist_matrix) <- paste( rld$dex, colnames(rld), sep = "-" )
colnames(sample_rld_dist_matrix) <- NULL
rld_colors                       <- colorRampPalette( rev(brewer.pal(9, "Oranges")) )(255)
png("vsd_heatmap.png",width=2000,height=2000,units="px",res=300,pointsize=10)
pheatmap(sample_vsd_dist_matrix,clustering_distance_rows=sample_vsd_dists,clustering_distance_cols=sample_vsd_dists,col=vsd_colors)
dev.off()
png("rld_heatmap.png",width=2000,height=2000,units="px",res=300,pointsize=10)
pheatmap(sample_rld_dist_matrix,clustering_distance_rows=sample_rld_dists,clustering_distance_cols=sample_rld_dists,col=rld_colors)
dev.off()
png("vsd_pca.png",width=2000,height=2000,units="px",res=300,pointsize=10)
plotPCA(vsd, intgroup = "dex")
dev.off()
png("rld_pca.png",width=2000,height=2000,units="px",res=300,pointsize=10)
plotPCA(rld, intgroup = "dex")
dev.off()
png("volcano_plot.png",width=2000,height=2000,units="px",res=300,pointsize=10)
with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-3,3)))
with(subset(res, padj<.01 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res, padj<.01 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
dev.off()
png("de_heatmap.png",width=2000,height=2000,units="px",res=300,pointsize=10)
heatmap.2(log2(sig_de_gene_df))
dev.off()
